# Generated by Django 4.2.2 on 2023-09-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psmrequest',
            name='date_applied',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='psmrequest',
            name='expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='psmrequest',
            name='psm_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='psmrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
