# Generated by Django 4.2.2 on 2023-09-14 06:42

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_psmrequest_date_applied_psmrequest_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psmrequest',
            name='comment',
            field=models.FileField(default=user.models.get_default_comment_file, upload_to='commentPSM/'),
        ),
    ]
