# Generated by Django 4.2.2 on 2023-09-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_psmrequest_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceletterpsm',
            name='document',
            field=models.FileField(upload_to='ReferenceLetterPSM'),
        ),
    ]
