# Generated by Django 4.2.2 on 2023-09-24 06:14

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_referenceletterpsm_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceletterpsm',
            name='document',
            field=models.FileField(upload_to=user.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='requestletterpsm',
            name='document1',
            field=models.FileField(upload_to=user.models.custom_upload_to),
        ),
    ]
