# Generated by Django 4.2.2 on 2023-09-24 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_referenceletterpsm_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psmrequest',
            name='referenceletterpsm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.referenceletterpsm'),
        ),
        migrations.AddField(
            model_name='psmrequest',
            name='requestletterpsm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.requestletterpsm'),
        ),
    ]
