# Generated by Django 4.2.2 on 2023-09-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_psmrequest_referenceletterpsm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psmrequest',
            name='date_applied',
            field=models.DateField(auto_now_add=True),
        ),
    ]
