# Generated by Django 4.2.2 on 2023-10-03 03:07

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_psmrequest_date_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=user.models.custom_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=user.models.custom_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=user.models.custom_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSRRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor_name', models.CharField(blank=True, max_length=255)),
                ('approved_psm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.psmrequest')),
                ('csv_excel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.csv')),
                ('raw_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.rawdata')),
                ('survey_report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.surveyreport')),
            ],
        ),
    ]
