# Generated by Django 4.2.2 on 2023-10-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_csv_rawdata_surveyreport_csrrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psmrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
