# Generated by Django 4.2.2 on 2023-10-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_psmrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psmrequest',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
