# Generated by Django 4.2.2 on 2023-11-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_psmrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psmrequest',
            name='referenceletterpsm',
        ),
        migrations.DeleteModel(
            name='ReferenceLetterPSM',
        ),
    ]
