# Generated by Django 4.2.2 on 2023-11-08 04:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_psmrequest_referenceletterpsm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csrrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='csrrequest',
            name='approved_psm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='csr_requests', to='user.psmrequest'),
        ),
        migrations.AlterField(
            model_name='csrrequest',
            name='csv_excel',
            field=models.FileField(null=True, upload_to='csr/csv_excel/'),
        ),
        migrations.AlterField(
            model_name='csrrequest',
            name='raw_data',
            field=models.FileField(null=True, upload_to='csr/raw_data/'),
        ),
        migrations.AlterField(
            model_name='csrrequest',
            name='survey_report',
            field=models.FileField(null=True, upload_to='csr/survey_report/'),
        ),
        migrations.AlterField(
            model_name='csrrequest',
            name='surveyor_name',
            field=models.CharField(max_length=255),
        ),
    ]
