# Generated by Django 4.2.2 on 2023-11-08 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0013_csrrequest_created_at_alter_csrrequest_approved_psm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('staff', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('psm_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.psmrequest')),
            ],
        ),
    ]
