# Generated by Django 4.2.2 on 2023-10-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_psmrequest_status'),
        ('mlsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('staff', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('psm_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.psmrequest')),
            ],
        ),
    ]
