# Generated by Django 4.2.4 on 2023-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyor',
            name='name',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
