# Generated by Django 4.2.4 on 2023-11-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyor', '0003_alter_surveyor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
