# Generated by Django 4.0.6 on 2024-01-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_island_atoll'),
        ('surveyor', '0006_csrrequest_status_psmrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psmrequest',
            name='island',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.island'),
        ),
    ]
